[tool.poetry]
name = "ml-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
  { include = "src", from = "." }
]

[tool.poetry.dependencies]
python = "^3.9"
lightning = "^2.3.2"
hydra-core = "^1.3.2"
hydra-colorlog = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"
wandb = "^0.17.4"
transformers = "^4.42.3"
datasets = "^2.20.0"
rootutils = "^1.0.7"
pre-commit = "^3.7.1"
rich = "^13.7.1"
pytest = "^8.2.2"
plotly = "^5.22.0"
matplotlib = "^3.9.1"
timm = "^1.0.7"
ultralytics = "^8.2.48"
numpy = ">=1.23.0,<2.0.0"
pillow = "^10.4.0"
torchvision = {version = "^0.19.0", allow-prereleases = true}

# [tool.poetry.group.cpu]
# optional = true

# [tool.poetry.group.cpu.dependencies]
# torch = { version = "^2.4.0", source = "torch_cpu", markers = "extra=='cpu' and extra!='gpu'", allow-prereleases = true }

# [tool.poetry.group.gpu]
# optional = true

# [tool.poetry.group.gpu.dependencies]
# torch = { version = "^2.4.0", source = "torch_cuda", markers = "extra=='gpu' and extra!='cpu'", allow-prereleases = true }


# [tool.poetry.extras]
# cpu = ["torch"]
# gpu = ["torch"]

# [[tool.poetry.source]]
# name = "torch_cpu"
# url = "https://download.pytorch.org/whl/nightly/cpu"
# priority = "explicit"


# [[tool.poetry.source]]
# name = "torch_cuda"
# url = "https://download.pytorch.org/whl/nightly/cu121"
# priority = "explicit"
onnx = "^1.16.2"
onnxscript = "^0.1.0.dev20240902"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.0"
black = "^24.4.2"
isort = "^5.13.2"
jupyter = "^1.0.0"
statsmodels = "^0.14.2"
scikit-learn = "^1.5.1"
paramiko = "^3.4.0"
fabric = "^3.2.2"
netron = "^7.8.2"
torch-tb-profiler = "^0.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
